DROP DATABASE IF EXISTS yumpSF;

CREATE DATABASE yumpSF;

USE yumpSF;

CREATE TABLE restaurants (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name TEXT NOT NULL 
);

CREATE TABLE dishes (
  id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
  restaurant_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  price DECIMAL(3,2) NOT NULL,
  description VARCHAR(200) NOT NULL,
  reviews INTEGER NOT NULL 
);

CREATE TABLE dishes_photos (
  id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
  photos_id INTEGER NOT NULL,
  dishes_id INTEGER NOT NULL
);

CREATE TABLE photos (
  id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
  url VARCHAR(200) NOT NULL,
  caption VARCHAR(200) NOT NULL
);

