CREATE DATABASE IF NOT EXISTS yumpSF;

USE yumpSF;

CREATE TABLE restaurants (
id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
name TEXT NOT NULL
);

CREATE TABLE dishes (
  id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
  restaurant_id INTEGER NOT NULL FOREIGN KEY,
  name TEXT NOT NULL,
  price DECIMAL(3,2) NOT NULL,
  description VARCHAR(20) NOT NULL 
);

CREATE TABLE photos (
  id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
  url VARCHAR(200) NOT NULL,
  caption VARCHAR (200) NOT NULL
);

CREATE TABLE dishes_photos (
  id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
  photos_id INTEGER NOT NULL FOREIGN KEY,
  dishes_id INTEGER NOT NULL FOREIGN KEY
);


-- INSERT INTO restaurants (name) VALUES(?, ?), 


